name-template: 'v$RESOLVED_VERSION 🧜🏽‍♀️'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    label:
      - 'feature'
  - title: '🐛 Bug Fixes'
    label:
      - 'bug'
  - title: '🧰 Maintenance'
    labels:
      - 'test'
      - 'chore'
      - 'refactor'
      - 'documentation'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'feature'
  patch:
    labels:
      - 'bug'
      - 'test'
      - 'chore'
      - 'refactor'
      - 'documentation'
  default: patch
template: |
  ## Changes
  $CHANGES
autolabeler:
  - label: feature
    branch:
      - '/^feat(ure)?[/-].+/'
  - label: bug
    branch:
      - '/^fix[/-].+/'
  - label: chore
    branch:
      - '/^chore[/-].+/'
  - label: refactor
    branch:
      - '/(refactor|refactoring)[/-].+/'
  - label: documentation
    branch:
      - '/doc(umentation)[/-].+/'
    files:
      - '*.md'
  - label: test
    branch:
      - '/^test(ing)?[/-].+/'
