name: Sync labels

on:
  push:
    branches:
      - production
  path:
    - .github/action-label-syncer-labels.yml
jobs:
  build:
    name: Sync labels
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: micnncim/action-label-syncer@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          manifest: .github/action-label-syncer-labels.yml
